### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by almp1** [LM-Commons/LmcCors#4]
Hi, 

I made the following settings:

Copy lmc_cors.global to /config/autoload/lmc_cors.local.php

In /config/modules.config.php

`return [
    'Laminas\Session',
    'Laminas\Db',
    'Laminas\I18n',
    'Laminas\Filter',
    'Laminas\Hydrator',
    'Laminas\Mvc\Console',
    'Laminas\Router',
    'Laminas\Validator',
    'Laminas\DeveloperTools',
    'Laminas\Cache',
    'LmcCors',
    'Application',`

In my modules.config.php /module/Login/Module.php

`<?php

/**
 * @see       https://github.com/laminas/laminas-mvc-skeleton for the canonical source repository
 * @copyright https://github.com/laminas/laminas-mvc-skeleton/blob/master/COPYRIGHT.md
 * @license   https://github.com/laminas/laminas-mvc-skeleton/blob/master/LICENSE.md New BSD License
 */

declare(strict_types=1);

namespace Login;

use Laminas\Router\Http\Literal;
use Laminas\Router\Http\Segment;
use Laminas\ServiceManager\Factory\InvokableFactory;
use LmcCors;

return [
    'lmc_cors' => [
        'allowed_origins' => ['*'],
        'allowed_methods' => ['GET', 'POST', 'DELETE'],
    ],    
    'router' => [
        'routes' => [
            'login' => [
                'type'    => Segment::class,
                'options' => [
                    'route'    => '/login[/:action]',
                    'defaults' => [
                        'controller' => Controller\LoginController::class,
                        'action'     => 'index',
                        \LmcCors\Options\CorsOptions::ROUTE_PARAM => [
                            'allowed_methods' => ['POST'],
                        ],                        
                    ],
                ],
            ],
        ],
    ],
    'view_manager' => [
        'display_not_found_reason' => true,
        'display_exceptions'       => true,
        'strategies' => [
	        'ViewJsonStrategy',
	    ],
    ],
];
`
Even so, I still receive the message that CORS is not enabled

`URL de Solicitação: http://www.apivf.local/login/login
Política de referenciador: strict-origin-when-cross-origin
Cabeçalhos provisórios são mostrados
Accept: application/json, text/plain, */*
Content-Type: application/json
Referer: http://www.appvf.local/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36 Edg/89.0.774.57`

`URL de Solicitação: http://www.apivf.local/login/login
Método de Solicitação: OPTIONS
Código de Status: 200 OK
Endereço Remoto: 127.0.0.1:80
Política de referenciador: strict-origin-when-cross-origin
Access-Control-Allow-Headers: Authorization
Access-Control-Allow-Methods: POST
Access-Control-Allow-Origin: http://www.appvf.local
Access-Control-Max-Age: 0
Connection: Keep-Alive
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Date: Thu, 25 Mar 2021 02:48:15 GMT
Keep-Alive: timeout=5, max=100
Server: Apache/2.4.46 (Win64) OpenSSL/1.1.1j PHP/7.4.15
X-Powered-By: PHP/7.4.15
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: pt-BR,pt;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Access-Control-Request-Headers: content-type
Access-Control-Request-Method: POST
Cache-Control: no-cache
Connection: keep-alive
Host: www.apivf.local
Origin: http://www.appvf.local
Pragma: no-cache
Referer: http://www.appvf.local/
Sec-Fetch-Mode: cors
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36 Edg/89.0.774.57`

Can you help me with any tips, or something I'm doing wrong?

Thank you very much

**Comment by visto9259** [comment]
@almp1,
I think you are missing a config in your `lmc_cors`.
Add the following:

```php
'lmc_cors' => [
   'allowed_origins' => ['*'], 
   'allowed_methods' => ['GET', 'POST', 'DELETE', 'OPTIONS'],
   'allowed_headers' => ['Authorization'],
]
Let me know if that solves your issue.

**Comment by almp1** [comment]
Hello @visto9259 

Thanks for the answer.
It is very simple to use, congratulations on the script.

My problem was in sending the parameter "withCredentials: true" in javascript. When I removed this parameter, CORS worked correctly.

I will check now why I am not able to use cookies / session

Thank you very much

**Comment by visto9259** [comment]
Closing
